In [72]:
import pandas as pd
import numpy as np
from sklearn import linear_model
file_path = 'sample_data/hiring.csv'

In [77]:
df = pd.read_csv(file_path)
print(df)

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000


In [79]:
help_dict = { 
    'one': 1, 
    'two': 2, 
    'three': 3, 
    'four': 4, 
    'five': 5, 
    'six': 6, 
    'seven': 7, 
    'eight': 8, 
    'nine': 9, 
    'zero' : 0,
    'NaN' : 0,
    'nan' : 0,
    'ten' : 10,
    'eleven' : 11,
    'test_score(out of 10)' : 'test',
    'interview_score(out of 10)' : 'interview',
    'salary($)' : 'salary'
}

In [89]:
df['experience'] = df['experience'].replace(help_dict)
df['experience'].fillna(0, inplace=True)
df['test'].fillna(0.0, inplace=True)

df.rename(columns=help_dict, inplace = True)
df.to_csv(file_path, index=False)

df

experience  test  interview  salary
0           0   8.0          9   50000
1           0   8.0          6   45000
2           5   6.0          7   60000
3           2  10.0         10   65000
4           7   9.0          6   70000
5           3   7.0         10   62000
6          10   0.0          7   72000
7          11   7.0          8   80000

In [90]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('salary',axis='columns'),df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [91]:
reg.coef_

array([3077.8642085 ,  999.7856246 , 2118.48834717])

In [92]:
reg.intercept_

24823.523106605797

In [93]:
reg.predict([[2, 9, 6]])

array([52688.25222797])

In [94]:
reg.predict([[12, 10, 10]])

array([92940.63332619])